import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

TRANSFORMER_EMB_DIM = 128
TRANSFORMER_NHEAD = 4
TRANSFORMER_NUM_ENCODER_LAYERS = 2
TRANSFORMER_NUM_DECODER_LAYERS = 2
TRANSFORMER_FF_DIM = 512
TRANSFORMER_DROPOUT = 0.1

TRANSFORMER_BATCH_SIZE = 32
TRANSFORMER_EPOCHS = 50
TRANSFORMER_LR = 1e-4
TRANSFORMER_MAX_LEN = 60